CREATE DATABASE CINE;

USE CINE;

CREATE TABLE PELICULAS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL UNIQUE,
DUR_MIN INT NOT NULL
);

DESC PELICULAS;

CREATE TABLE CLIENTES(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45),
APELLIDO VARCHAR(45) NOT NULL,
EMAIL VARCHAR(45) NOT NULL UNIQUE
);

DESC CLIENTES;

CREATE TABLE SALAS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(45) NOT NULL,
N_ASIENTOS INT NOT NULL
);

DESC SALAS;

CREATE TABLE FUNCIONES(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PELICULA INT NOT NULL,
ID_SALA INT NOT NULL,
HORA_INICIO DATETIME NOT NULL,
FOREIGN KEY (ID_PELICULA) REFERENCES PELICULAS(ID),
FOREIGN  KEY (ID_SALA) REFERENCES SALAS(ID)
);

DESC FUNCIONES;

CREATE TABLE ASIENTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_SALA INT NOT NULL,
FILA CHAR(2) NOT NULL,
NUMERO INT NOT NULL,
FOREIGN KEY (ID_SALA) REFERENCES SALAS(ID)
);

DESC ASIENTOS;

CREATE TABLE RESERVACIONES(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_FUNCION INT NOT NULL,
ID_CLIENTE INT NOT NULL,
FOREIGN KEY (ID_FUNCION) REFERENCES FUNCIONES(ID),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);

DESC RESERVACIONES;

CREATE TABLE ASIENTOS_RESERVADOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_RESERVACION INT NOT NULL,
ID_ASIENTO INT NOT NULL,
FOREIGN KEY (ID_RESERVACION) REFERENCES RESERVACIONES(ID),
FOREIGN KEY (ID_ASIENTO) REFERENCES ASIENTOS(ID)
);

DESC ASIENTOS_RESERVADOS;